# Generated by Django 3.0.3 on 2020-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followusers',
            name='tag',
            field=models.CharField(help_text='Enter your nickname', max_length=200, null=True),
        ),
    ]
