# Generated by Django 3.0.3 on 2020-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0002_followusers_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followusers',
            name='tag',
        ),
    ]
