# Generated by Django 3.0.3 on 2020-05-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0002_auto_20200516_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCircleFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circleOwner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.communityUsers')),
                ('circleUsers', models.ManyToManyField(help_text='Select Members', related_name='Following', to='streampage.communityUsers')),
            ],
        ),
    ]
