# Generated by Django 3.0.3 on 2020-05-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0003_usercirclefollowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCircleFollowing',
        ),
    ]
