# Generated by Django 3.0.3 on 2020-05-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0003_remove_followusers_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followusers',
            name='following',
        ),
    ]
