# Generated by Django 3.0.3 on 2020-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0004_delete_usercirclefollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='communityCountry',
            field=models.CharField(help_text='Select country', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='communities',
            name='communityLocation',
            field=models.CharField(help_text='Select province', max_length=2000, null=True),
        ),
    ]
