# Generated by Django 3.0.3 on 2020-05-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0004_remove_followusers_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followUsers',
        ),
    ]
