# Generated by Django 3.0.3 on 2020-03-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0004_auto_20200327_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='datatypeEditionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='datatypeEditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatypeeditor', to='streampage.communityUsers'),
        ),
    ]
