# Generated by Django 3.0.3 on 2020-05-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0005_delete_followusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.communityUsers')),
            ],
        ),
    ]
