# Generated by Django 3.0.3 on 2020-04-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0005_auto_20200328_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryHash', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('commentText', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('postCommentCreationDate', models.DateTimeField(null=True)),
                ('postCommentTag', models.CharField(help_text='Enter Post Tags', max_length=2000, null=True)),
                ('postCommentCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentcreator', to='streampage.communityUsers')),
                ('relatedCommunityforComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Communities')),
                ('relatedDatatypes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Datatypes')),
                ('relatedPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Posts')),
            ],
        ),
    ]
