# Generated by Django 3.0.3 on 2020-04-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0006_postcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='entryHash',
            new_name='commentHash',
        ),
    ]
