# Generated by Django 3.0.3 on 2020-05-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0006_mytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mytest',
        ),
    ]
