# Generated by Django 3.0.3 on 2020-04-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0007_auto_20200413_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='relatedDatatypes',
        ),
    ]
