# Generated by Django 3.0.3 on 2020-04-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0008_remove_postcomments_relateddatatypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postMetaHash', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('relatedCommunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Communities')),
                ('relatedDatatypes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Datatypes')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='relatedMeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.PostsMeta'),
        ),
    ]
