# Generated by Django 3.0.3 on 2020-04-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0011_postcomments_relatedmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='relatedPost',
        ),
    ]
