# Generated by Django 3.0.3 on 2020-04-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0012_remove_postcomments_relatedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmetahash',
            name='postCreationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postsmetahash',
            name='postCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmetacreator', to='streampage.communityUsers'),
        ),
    ]
