# Generated by Django 3.0.3 on 2020-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0013_auto_20200413_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='entryHash',
            field=models.CharField(help_text='Enter name of type', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='propertyName',
            field=models.CharField(help_text='Enter name of type', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='propertyValue',
            field=models.CharField(help_text='Enter name of type', max_length=2000, null=True),
        ),
    ]
