# Generated by Django 3.0.6 on 2020-05-12 08:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0014_auto_20200508_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
