# Generated by Django 3.0.3 on 2020-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0015_activitystreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='subscribers',
            field=models.ManyToManyField(help_text='Select members', related_name='subscribers', to='streampage.communityUsers'),
        ),
    ]
