# Generated by Django 3.0.3 on 2020-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0017_auto_20200512_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmetahash',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='datatypes',
            name='subscribers',
            field=models.ManyToManyField(help_text='Select members', related_name='subscribers', to='streampage.communityUsers'),
        ),
    ]
