# Generated by Django 3.0.3 on 2020-05-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0018_auto_20200512_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatypes',
            name='datatypePhoto',
        ),
    ]
