# Generated by Django 3.0.3 on 2020-05-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0019_remove_datatypes_datatypephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('description', models.CharField(help_text='Enter name of type', max_length=2000, null=True)),
                ('reportPostCreationDate', models.DateTimeField(null=True)),
                ('relatedCommunityforComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.Communities')),
                ('relatedMeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streampage.PostsMetaHash')),
                ('reportPostCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporttcreator', to='streampage.communityUsers')),
            ],
        ),
    ]
