# Generated by Django 3.0.3 on 2020-05-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0020_reportedposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedposts',
            old_name='relatedCommunityforComment',
            new_name='relatedCommunity',
        ),
    ]
