# Generated by Django 3.0.3 on 2020-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0021_auto_20200514_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityusers',
            name='userBio',
            field=models.CharField(help_text='Community Point', max_length=200, null=True),
        ),
    ]
