# Generated by Django 3.0.3 on 2020-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streampage', '0022_communityusers_userbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityusers',
            name='userBirthDay',
            field=models.CharField(help_text='Community Point', max_length=200, null=True),
        ),
    ]
